const fs = require('fs');

let content = fs.readFileSync('src/services/storage/repository.ts', 'utf8');

// Ensure accounts have business_id
const techAndRetailAccounts = `,
  {
    id: 'acc-tech-usd',
    business_id: 'comp-tech-002',
    name: 'SVB Operational Checking (USD)',
    name_json: JSON.stringify({
      en: 'SVB Operational Checking (USD)',
      uk: 'Операційний рахунок SVB (USD)',
      ru: 'Операционный счет SVB (USD)',
    }),
    type: 'bank',
    currency: 'USD',
    balance: 74200,
    initial_balance: 50000,
    initial_balance_date: '2026-02-15',
    responsible_person: 'Alexander Kovalenko',
    is_active: true,
    include_in_calendar: true,
    account_number: 'US98SVB1234567890',
    created_at: '2026-02-15T08:00:00Z',
    updated_at: '2026-09-01T10:00:00Z',
    source: 'manual',
    sync_status: 'synced',
    version: 1,
    owner_id: 'usr-owner-1',
  },
  {
    id: 'acc-tech-stripe',
    business_id: 'comp-tech-002',
    name: 'Stripe SaaS Acquiring (USD)',
    name_json: JSON.stringify({
      en: 'Stripe SaaS Acquiring (USD)',
      uk: 'Еквайринг Stripe SaaS (USD)',
      ru: 'Эквайринг Stripe SaaS (USD)',
    }),
    type: 'payment_wallet',
    currency: 'USD',
    balance: 18500,
    initial_balance: 10000,
    initial_balance_date: '2026-02-15',
    responsible_person: 'Alexander Kovalenko',
    is_active: true,
    include_in_calendar: true,
    created_at: '2026-02-15T08:00:00Z',
    updated_at: '2026-09-01T10:00:00Z',
    source: 'manual',
    sync_status: 'synced',
    version: 1,
    owner_id: 'usr-owner-1',
  },
  {
    id: 'acc-retail-cash',
    business_id: 'comp-retail-003',
    name: "Каса кав'ярень (Львів)",
    name_json: JSON.stringify({
      uk: "Каса кав'ярень (Львів)",
      ru: 'Касса кофеен (Львов)',
      en: 'Lviv Coffee Shops Cash Register',
    }),
    type: 'cash',
    currency: 'UAH',
    balance: 41200,
    initial_balance: 15000,
    initial_balance_date: '2026-03-01',
    responsible_person: 'Мельничук К. О.',
    is_active: true,
    include_in_calendar: true,
    created_at: '2026-03-01T08:00:00Z',
    updated_at: '2026-09-01T10:00:00Z',
    source: 'manual',
    sync_status: 'synced',
    version: 1,
    owner_id: 'usr-owner-1',
  },
  {
    id: 'acc-retail-bank',
    business_id: 'comp-retail-003',
    name: 'Райффайзен Банк (ФОП Мельничук)',
    name_json: JSON.stringify({
      uk: 'Райффайзен Банк (ФОП Мельничук)',
      ru: 'Райффайзен Банк (ФЛП Мельничук)',
      en: 'Raiffeisen Bank Account (FOP)',
    }),
    type: 'bank',
    currency: 'UAH',
    balance: 89600,
    initial_balance: 40000,
    initial_balance_date: '2026-03-01',
    responsible_person: 'Мельничук К. О.',
    is_active: true,
    include_in_calendar: true,
    account_number: 'UA443808050000026009876543210',
    created_at: '2026-03-01T08:00:00Z',
    updated_at: '2026-09-01T10:00:00Z',
    source: 'manual',
    sync_status: 'synced',
    version: 1,
    owner_id: 'usr-owner-1',
  }`;

if (!content.includes('acc-tech-usd')) {
  content = content.replace(
    /owner_id: 'usr-owner-1',\s*},\s*\];\s*const INITIAL_CATEGORIES/,
    "owner_id: 'usr-owner-1',\n  }" + techAndRetailAccounts + "\n];\n\nconst INITIAL_CATEGORIES"
  );
}

// Add sample transactions for tech and retail businesses
const techAndRetailTxs = `,
  {
    id: 'tx-tech-001',
    business_id: 'comp-tech-002',
    type: 'sale',
    date: '2026-09-10T11:00:00Z',
    account_id: 'acc-tech-stripe',
    amount: 14200,
    currency: 'USD',
    category_id: 'cat-inc-srv',
    description: 'Enterprise Cloud SaaS Subscription (Annual)',
    status: 'confirmed',
    idempotency_key: 'idemp-tech-001',
    created_at: '2026-09-10T11:00:00Z',
    updated_at: '2026-09-10T11:00:00Z',
    source: 'manual',
    sync_status: 'synced',
    version: 1,
    owner_id: 'usr-owner-1',
  },
  {
    id: 'tx-tech-002',
    business_id: 'comp-tech-002',
    type: 'expense',
    date: '2026-09-05T14:30:00Z',
    account_id: 'acc-tech-usd',
    amount: 4800,
    currency: 'USD',
    category_id: 'cat-exp-srv',
    description: 'AWS Cloud Hosting & AI Compute Cluster',
    status: 'confirmed',
    idempotency_key: 'idemp-tech-002',
    created_at: '2026-09-05T14:30:00Z',
    updated_at: '2026-09-05T14:30:00Z',
    source: 'manual',
    sync_status: 'synced',
    version: 1,
    owner_id: 'usr-owner-1',
  },
  {
    id: 'tx-retail-001',
    business_id: 'comp-retail-003',
    type: 'sale',
    date: '2026-09-12T19:00:00Z',
    account_id: 'acc-retail-cash',
    amount: 18400,
    currency: 'UAH',
    category_id: 'cat-inc-sale',
    description: "Денна виручка кав'ярень (Львів, Свободи + Франка)",
    status: 'confirmed',
    idempotency_key: 'idemp-ret-001',
    created_at: '2026-09-12T19:00:00Z',
    updated_at: '2026-09-12T19:00:00Z',
    source: 'manual',
    sync_status: 'synced',
    version: 1,
    owner_id: 'usr-owner-1',
  },
  {
    id: 'tx-retail-002',
    business_id: 'comp-retail-003',
    type: 'purchase',
    date: '2026-09-08T09:15:00Z',
    account_id: 'acc-retail-bank',
    amount: 12500,
    currency: 'UAH',
    category_id: 'cat-exp-cogs',
    description: 'Свіжообсмажена арабіка (100 кг) та серветки',
    status: 'confirmed',
    idempotency_key: 'idemp-ret-002',
    created_at: '2026-09-08T09:15:00Z',
    updated_at: '2026-09-08T09:15:00Z',
    source: 'manual',
    sync_status: 'synced',
    version: 1,
    owner_id: 'usr-owner-1',
  }`;

if (!content.includes('tx-tech-001')) {
  content = content.replace(
    /owner_id: 'usr-owner-1',\s*},\s*\];\s*const INITIAL_PAYMENTS/,
    "owner_id: 'usr-owner-1',\n  }" + techAndRetailTxs + "\n];\n\nconst INITIAL_PAYMENTS"
  );
}

fs.writeFileSync('src/services/storage/repository.ts', content, 'utf8');
console.log('Sample data for Multi-Business companies injected successfully!');
